---
kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: hugomods/hugo:exts-0.148.2
    commands:
      - hugo -e production --gc --minify --cleanDestinationDir --baseURL="/"

  - name: publish local
    image: plugins/s3
    settings:
        endpoint: s3.ebardelli.com
        bucket: homepage
        region: garage
        path_style: true
        access_key:
          from_secret: garage_access_key
        secret_key:
          from_secret: garage_secret_key
        source: public/**/*
        target: /
        strip_prefix: true

  - name: publish gh pages
    image: plugins/gh-pages
    settings:
      username:
        from_secret: gh_username
      password:
        from_secret: gh_token
      remote_url:
        from_secret: gh_repo
      target_branch: html
      pages_directory: public/

  - name: invalidate-cloudflare-cache
    image: jetrails/drone-cloudflare-caching
    settings:
        api_token:
            from_secret: cloudflare_token
        zone_identifier:
            from_secret: cloudflare_zone_identifier
        action: purge_everything

...
