---
kind: pipeline
type: docker
name: build

steps:
    - name: build hugo-academic image
      image: plugins/docker
      settings:
        dockerfile: Dockerfile
        username: 
          from_secret: docker_username
        password:
          from_secret: docker_password
        repo: ebardelli/hugo-academic
        tags: latest
...
