---
kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: klakegg/hugo:0.95.0-ext
    commands:
      - hugo -e production --gc --minify --cleanDestinationDir --baseURL="/"

  - name: publish local
    image: drillster/drone-rsync
    volumes:
      - name: www_dir
        path: /www
    commands:
      - rsync -rltvzc --delete --omit-dir-times --no-o --no-g public/ /www/

  - name: publish gh pages
    image: plugins/gh-pages
    settings:
      username:
        from_secret: gh_username
      password:
        from_secret: gh_token
      remote_url:
        from_secret: gh_repo
      target_branch: html
      pages_directory: public/

volumes:
- name: www_dir
  host:
    path: /data/www/ebardelli.com/public

---
kind: pipeline
type: docker
name: publish to UMich hosting

steps:
  - name: build
    image: klakegg/hugo:0.95.0-ext
    commands:
      - hugo -e production --gc --minify --cleanDestinationDir --baseURL="http://www-personal.umich.edu/~bardelli/"

  - name: publish UMich
    image: drillster/drone-rsync
    environment:
      SERVER:
        from_secret: server
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
    commands:
      - apk add --update --no-cache sshpass
      - sshpass -p "$PASSWORD" rsync -e "ssh -o StrictHostKeyChecking=no" -rltvzc --delete --omit-dir-times --no-o --no-g public/* $USERNAME@$SERVER:~/Public/html

...
