---
kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: hugomods/hugo:exts-0.148.2
    commands:
      - hugo -e production --gc --minify --cleanDestinationDir --baseURL="/"

  - name: S3 sync to garage
    image: peakcom/s5cmd:v2.3.0
    commands:
      - /s5cmd --endpoint-url=$AWS_ENDPOINT sync --delete public/ s3://homepage/
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: garage_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: garage_secret_key
      AWS_ENDPOINT: https://s3.ebardelli.com
      AWS_DEFAULT_REGION: garage

  - name: publish gh pages
    image: plugins/gh-pages
    settings:
      username:
        from_secret: gh_username
      password:
        from_secret: gh_token
      remote_url:
        from_secret: gh_repo
      target_branch: html
      pages_directory: public/

  - name: invalidate-cloudflare-cache
    image: jetrails/drone-cloudflare-caching
    settings:
        api_token:
            from_secret: cloudflare_token
        zone_identifier:
            from_secret: cloudflare_zone_identifier
        action: purge_everything

...
